name: Workflow for Codecov Action
on:
  push:
    branches: 
      - main
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest, macos-latest, windows-latest]
    steps:       
      - name: Install dependencies
        run: npm install

      - name: Run the tests and generate coverage report
        run: npm test -- --coverage    
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml,!./cache
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
  
   
      - name: Build
        run: npm run build

      - name: Deploy
        run: |
            git remote set-url origin https://${github_token}@github.com/${repository}
            npm run deploy
        env:
          github_token: ${{ secrets.CODECOV_TOKEN }}
          repository: ${{ github.repository }}
